### ISSUE TITLE
cannot reflect validator info

### ISSUE THREAD

**Issue by wim-web** [ElixirProtocol/testnet-3-issue-tracker#3]
response of https://api.testnet-3.elixirdev.xyz/validators//0x98e6d6165Ec7C742d72E220632585FfB88be1061

```
{
    "validator": {
        "jailed": false,
        "address": "0x98e6d6165Ec7C742d72E220632585FfB88be1061",
        "delegate_count": "1",
        "uptime_week": 0.0,
        "apy": 0.0,
        "display_name": null,
        "beneficiary": null,
        "total_delegated": "33000000000000000000000",
        "uptime_day": 0.0,
        "uptime_month": 0.0
    }
}
```

compose.yaml
```
services:
  # ADDRESS: 0x98e6d6165Ec7C742d72E220632585FfB88be1061
  ev:
    image: elixirprotocol/validator:3.1.0
    restart: unless-stopped
    ports:
      - "17690:17690"
    volumes:
      - ./elixir/data:/data
    env_file:
      - ./elixir/.env
```

```
ls -a elixir/
.  ..  data  .env
```

.env (Masked IP and private)
```
ENV=testnet-3

STRATEGY_EXECUTOR_IP_ADDRESS=***
STRATEGY_EXECUTOR_DISPLAY_NAME=nya
STRATEGY_EXECUTOR_BENEFICIARY=0xE110A32C3e484d8f26f4325c3563CE56C00d0530
SIGNER_PRIVATE_KEY=***
```
